### ISSUE TITLE
how to add the beam searching in your paper ?

### ISSUE THREAD

**Issue by robotzheng** [toru34/li_emnlp_2017#1]
EPOCH: 350, Train Cost: 17.964 (NLL: 17.960, KL: 0.004), Valid Cost: 22.045 (NLL: 22.044, KL: 0.001)
EPOCH: 400, Train Cost: 14.856 (NLL: 14.852, KL: 0.003), Valid Cost: 18.668 (NLL: 18.667, KL: 0.001)
EPOCH: 450, Train Cost: 11.773 (NLL: 11.768, KL: 0.004), Valid Cost: 15.846 (NLL: 15.845, KL: 0.001)
EPOCH: 500, Train Cost: 9.404 (NLL: 9.400, KL: 0.004), Valid Cost: 16.374 (NLL: 16.355, KL: 0.019)
EPOCH: 550, Train Cost: 7.659 (NLL: 7.654, KL: 0.005), Valid Cost: 13.963 (NLL: 13.963, KL: 0.000)
EPOCH: 600, Train Cost: 6.423 (NLL: 6.420, KL: 0.003), Valid Cost: 11.698 (NLL: 11.692, KL: 0.007)
EPOCH: 650, Train Cost: 5.236 (NLL: 5.231, KL: 0.006), Valid Cost: 10.556 (NLL: 10.549, KL: 0.007)

true_x: 【 全球 购 】 布鲁克斯 ( BROOK ' S ) 【 挂 耳 滤泡 】 日本 直邮黑 咖啡 精品 组合 特惠 装
true_y: 布鲁克斯 黑 咖啡 组合装 </s>
pred_y: 周家口 招牌 酱牛肉 </s> 花茶 280g </s> 时代 挂 意式 种 小种红茶 克 * 20 包 </s> 茯苓 * 15 * 1 </s> 瑞 月饼 系列 肠 广式 月饼 礼盒装 大地 384g </s> 超市 * 6 茶 ） 罐装 克 礼盒装 </s> 煎 小种红茶 120g </s> 750 75 克 240g </s> 45g 罐 买 2 罐 ) </s> 超市 / 盒装 x750ml </s> 甜甜 高蛋白 高蛋白 全脂 花果茶 100g </s> 茶篓 套装 礼盒 套餐 </s> 姜茶 铁盒 1000g </s> 甜甜 全脂 圈 组合装 8 盒 * 2 袋 x4 包 装 </s> 脆皮 牛 面皮 儿 200gx100 包 </s>

true_x: 火麻糊 800g 礼盒装 广西 巴马 特产 营养 米糊 食品 火麻仁 粉无糖代餐 粉糊 黑墨 米粉 糊 农家 早餐 冲泡
true_y: 火麻糊 800g 礼盒装 </s>
pred_y: 小仓娃 红薯 粉皮 2500g5 袋装 礼盒装 </s> 玉山 奶粉 柠檬茶 250ml * 12 赠辣 12 </s> 装共 10g </s> 煎 进口 小 一丁 饮料 茯砖 红茶 克 * 2 罐 / </s> 750 克 克 * 4 </s> 自产土 红糖 姜茶 </s> 癸巳 片 250 克 * 1 袋装 </s> 750 块 克 五香 自产土 猪肉 脯 150g </s> 超市 </s> 色素 8 种 简装 </s> 橘子 250ml </s> 750 克 共 </s> 癸巳 薄壳核桃 陶瓷 1 元装 篓 千克 </s> 超市 进口 有机 牛 绿豆 礼盒 </s> 45g 瓶装 礼盒 包 </s> 55g 袋装 礼盒 </s> U 碗

true_x: Member ' s Mark 精选 单片 黑木耳 300g Item # : 437988
true_y: Member ' s Mark 单片 黑木耳 300g </s>
pred_y: Member ' s Mark 单片 黑木耳 100g </s> 50g </s> 喜羊 手提袋 Espresso 纯牛奶 60g </s> 鲜花店 </s> 茶篓 5 </s> 355ml </s> 355ml 花果茶 1.5 kg </s> 选一 </s> 玉山 奶粉 850g * 10 提 </s> 小火锅 配送 进口 大礼包 </s> 花粉 </s> 煎 5 个装 纸盒装 买 12 袋 型 1500 支 共 258 258 258 】 20 只 只 母 3.4 KG </s> 66g 400 </s> 50g </s> 小火锅 木质 </s> 温岭 </s> 只 嘟嘟 桑葚 他 麦 坚果 乳粉 </s> 色素 1 粒 </s> 脆皮 综合 薏米 粽 </s> 45g 2 120g </s> 1.5 八月

true_x: 中秋 中粮 山萃 礼品 册 礼品 卡 自选 册 5000 型 提货 券 20 选一
true_y: 中粮 山萃 礼品 自选 册 5000 型 提货 券 20 选一 </s>
pred_y: 御之满 米苏 水果 全脂 纯牛奶 礼盒装 </s> 250g </s> 末 简装 </s> 超市 简装 </s> 对 6 </s> 对 6 袋 红豆 进口 味 矿泉水 麦芯 整箱 500ml </s> 玉山 </s> 小火锅 进口 一品 1kg 礼品 卡券 阳澄湖 大闸蟹 提货 卡 </s> 癸巳 皮蛋 礼盒装 </s> 花粉 4.5 300 </s> 癸巳 干脆 姜丝 357 克 公 25g ) 公 </s> 武威 一丁 33 两 膳食 海鲜 礼盒 </s> 简装 1 粒 150g 克 </s> 益生菌 800 </s> 两 癸巳 驴肉 </s> 只母 波板 休闲 薏仁 盐焗鸡 35g 350ml * 2 </s> 勺 超市 1500g 罐 / 罐 * 2

true_x: 沂蒙 公社 山楂 条 280g * 1 袋 0 添加 山楂 制品 山楂片 新鲜 儿童 零食 山东 特产 蜜饯 休闲
true_y: 沂蒙 公社 山楂 条 280g * 1 袋 </s>
pred_y: 沂蒙 公社 花生 味 格 仁 400g </s> 750 系列 猪舌 400g </s> 227ml 夹饼 高粱米 克 装 ） 整箱 ) </s> 一刻 翅 4 13g * 6 块 小包 </s> 橘子 无糖 核桃 茶 茶 35g </s> 12 盒 京东 罐 超市 罐 超市 【 袋装 </s> 一刻 城 袋 8 4 1 支 装 560g </s> 颗粒 218g </s> 66g 饼 360g </s> 时代 年 韩国 茶 3 茶茶 浓香型 配送 </s> 超市 袋装 5 罐 * 4 </s> 12 莲蓉 咖喱 500ml 礼盒装 篓 克 * 1 + 月 干 5 斤 </s> 66g 袋装 </s>

true_x: 金赛 黑 苦荞 火麻茶 礼盒装 6 盒 x5gx16 包 广西 巴马 火麻茶
true_y: 金赛 火麻茶 礼盒装 6 盒 </s>
pred_y: 阳农汇鲜 白菜 干 250g </s> 50g </s> 玉山 嘜 优惠 年 10 克 </s> 鲜花店 </s> 茶篓 </s> 超市 袋 50 只装 </s> 公 玉山 罐装 88 礼盒装 </s> 同 42 绿维米 900g 13g * 牛肉 48 12 包 * 1 </s> 癸巳 188g 进口 5 零食 8 盒 </s> 日式 挂 速溶 两 320g </s> 超市 </s> 茶篓 </s> 超市 天鹅 58g 简 花果茶 茶叶 茶 168g </s> 日式 挂 添福 * 238g * 2 罐 / 箱 </s> 自产土 洋槐 百花 208gx12 盒 * 2 罐 / 箱 </s> 款 袋装 500 克 * 2 袋装 </s>

true_x: 御之满 嘉乡 斋 粽子 礼盒 端午节 嘉兴 南方 肉 粽
true_y: 御之满 嘉乡 斋 粽子 礼盒 </s>
pred_y: 御之满 卡册 卡 卡 型 提货 券 </s> 癸巳 柳州 即食 白茶 * 6 </s> 勺 对装 * 12 进口 饮用水 ) 12 对装 超市 超市 超市 超市 超市 礼盒装 </s> 进口 公主 月饼 龙井茶 叶 </s> 250g </s> 小火锅 袋装 </s> 德运 城 配送 礼盒装 礼品 册 2198 提货 选一 </s> 癸巳 胚芽 茶 </s> 癸巳 年 装 黑茶 500g </s> 官方 1 只 </s> 癸巳 g 超市 + 5 甜心 吉 册 3 </s> 只母 ） </s> 355ml </s> 卷 4.0 苏打饼干 </s> 颐府 咸蛋 泡菜 毫升 * 3 只 </s> 玉山 茶书 老人 菲尔 】 吉

true_x: 红果 人 鲜果 山楂 条 500g * 2 全 独立 包装 山楂片 山楂 干 无 添加 宝宝 零食
true_y: 红果 人 鲜果 山楂 条 500g * 2 </s>
pred_y: 云潞 法兰绒 速溶 咖啡 美味 坚果 豆 + 饮 2 70g * 6 袋 </s> 750 配送 </s> 超市 包邮 </s> 铁盒 橄榄油 </s> 45g 饼 50 只装 </s> 小火锅 超市 礼盒装 </s> 45g 克 50 元装 </s> 单泡 唛 鱼 薄荷 酱 120g </s> 癸巳 * 进口 5 100 克 </s> 100gx2 只 进口 高钙 蛋糕 </s> 对 15 条 </s> 茶篓 </s> g 度甜 秋 槟城 菜 礼盒装 480g 组合装 </s> 红茶 茶 盒装 罐装 </s> 麦香 葡萄酒 礼盒装 独立 土豆片 克 </s> 45g 2 茶叶 约 罐 * 3 </s> 自产土 火鸡 支 粥 70g </s>

we use 4000+ data to training the model, but it still not good enough, how to add the beam searching?
thanks.

**Comment by toru34** [comment]
@robotzheng 

Recently I switched tf to dynet, so I will re-implement this paper in dynet with beam search. Please wait for a little.

Thank you

**Comment by toru34** [comment]
and this is not my paper.

thanks

**Comment by toru34** [comment]
I added dynet version with beam search, so please try it.

thanks
